# Generated by Django 4.2.7 on 2026-03-01 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('salary_max', models.FloatField(blank=True, null=True)),
                ('demand_level', models.CharField(choices=[('high', 'High Demand'), ('medium', 'Medium Demand'), ('low', 'Low Demand')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('scale', 'Likert Scale (1-10)'), ('choice', 'Multiple Choice (A/B/C/D)')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text='{"A": "Option A", "B": "Option B"...}', null=True)),
                ('category', models.CharField(help_text='cognitive, motivation, interests, etc.', max_length=50)),
                ('weight', models.FloatField(default=1.0, help_text='Feature importance weight')),
                ('order', models.IntegerField(help_text='Display order in quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('domain', 'Domain Knowledge')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('top_career_1', models.CharField(blank=True, max_length=255, null=True)),
                ('score_1', models.FloatField(blank=True, null=True)),
                ('top_career_2', models.CharField(blank=True, max_length=255, null=True)),
                ('score_2', models.FloatField(blank=True, null=True)),
                ('top_career_3', models.CharField(blank=True, max_length=255, null=True)),
                ('score_3', models.FloatField(blank=True, null=True)),
                ('top_career_4', models.CharField(blank=True, max_length=255, null=True)),
                ('score_4', models.FloatField(blank=True, null=True)),
                ('top_career_5', models.CharField(blank=True, max_length=255, null=True)),
                ('score_5', models.FloatField(blank=True, null=True)),
                ('explanation', models.JSONField(blank=True, help_text='Why these careers match', null=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('years_experience', models.FloatField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.CharField(help_text='A, B, C, D, or numeric 1-10', max_length=255)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz Answers',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='career_app.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.skill')),
            ],
            options={
                'verbose_name_plural': 'Career Skills',
                'unique_together': {('career', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Mid-Level'), (3, 'Senior')])),
                ('duration_months', models.IntegerField()),
                ('description', models.TextField()),
                ('skills_to_learn', models.JSONField(help_text='List of skills needed at this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='career_app.career')),
            ],
            options={
                'ordering': ['career', 'stage'],
                'unique_together': {('career', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'career')},
            },
        ),
    ]
