# Generated by Django 4.2.7 on 2026-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('business', 'Business'), ('engineering', 'Engineering'), ('creative', 'Creative'), ('education', 'Education'), ('science', 'Science'), ('other', 'Other')], default='other', help_text='Industry category', max_length=50),
        ),
    ]
