# Generated by Django 4.2.7 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_career_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='profile_snapshot',
            field=models.JSONField(blank=True, help_text='Profile chart data (abilities/work_style/interests)', null=True),
        ),
        migrations.AddField(
            model_name='userresult',
            name='top_careers_snapshot',
            field=models.JSONField(blank=True, help_text='Full top careers payload from prediction response', null=True),
        ),
    ]
